json.id product.id
json.name product.name
json.price product.price
json.description product.description
json.supplier product.supplier
json.images product.images
json.createdAt product.created_at
json.updatedAt product.updated_at
json.isDiscounted product.is_discounted?
json.tax product.tax
json.total product.total
